### PR TITLE
padding added to the  class container  

### PR DESCRIPTION
**Pull request by suyashchauhan**

### CODE REVIEW

**Comment by faraazahmad** [comment]
Can you add the before and after screenshots on desktop and mobile screen size?

**Comment by suyashchauhan** [comment]
### Mobile
_before_
WhatsApp Image 2020-09-03 at 6 36 05 PM
_**After**_
WhatsApp Image 2020-09-03 at 6 43 00 PM

**Comment by suyashchauhan** [comment]
### DESKTOP
_Before_
x2

**_After_**
x1

**Comment by faraazahmad** [comment]
I need the space on the left and right to be equal. Looks like its an issue with the CSS Grid rather than `.container`

**Comment by faraazahmad** [comment]
Closing due to inactivity. Issue was solved by #7 (Thank your for contributing though, I really appreciate it)

**Pull request closed without merging**
